# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Document\User: sha512
    providers:
        facebook:
            id: user.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: /logout
            guard:
                authenticators:
                    - user.login_authenticator
                    - o_auth.facebook_authenticator
                    - o_auth.google_authenticator
                entry_point: user.login_authenticator
