services:
    user.login_authenticator:
        class: UserBundle\Security\LoginAuthenticator
        arguments: ["@service_container"]
    user.user_provider:
        class: UserBundle\Provider\UserProvider
        arguments: ["@service_container"]
